Repository kantabile/sonarkube, pull requests merged in 2023-02, with the labels that each got.

#49 RSPEC-5961, RSPEC-5958, RSPEC-5785, RSPEC-5778
  _posts/java/2023-01-29-RSPEC-5778.md
  _posts/java/2023-01-29-RSPEC-5785.md
  _posts/java/2023-01-29-RSPEC-5958.md
  _posts/java/2023-01-29-RSPEC-5961.md
Labels: tests

#50 RSPEC-5776, RSPEC-3415, RSPEC-1607, RSPEC-5841
  _posts/java/2023-01-30-RSPEC-1607.md
  _posts/java/2023-01-30-RSPEC-3415.md
  _posts/java/2023-01-30-RSPEC-5776.md
  _posts/java/2023-01-30-RSPEC-5841.md
Labels: tests

#48 RSPEC-5261, RSPEC-4144, RSPEC-3457
  _posts/java/2023-01-28-RSPEC-3457.md
  _posts/java/2023-01-28-RSPEC-4144.md
  _posts/java/2023-01-28-RSPEC-5261.md
Labels: 번역, ⭐ 리뷰 반영했어요 ⭐, confusing

#55 RSPEC-1479, RSPEC-1700, RSPEC-3776
  _posts/java/2023-02-02-RSPEC-1479.md
  _posts/java/2023-02-02-RSPEC-1700.md
  _posts/java/2023-02-02-RSPEC-3776.md
Labels: 번역, brain-overload

#51 docs: RSPEC-1141, RSPEC-2675, RSPEC-3042, RSPEC-3358
  _posts/java/2023-02-01-RSPEC-1141.md
  _posts/java/2023-02-01-RSPEC-2675.md
  _posts/java/2023-02-01-RSPEC-3042.md
  _posts/java/2023-02-01-RSPEC-3358.md
Labels: 번역, ⭐ 리뷰 반영했어요 ⭐, confusing

#56 RSPEC-1854, RSPEC-1940, RSPEC-2710, RSPEC-5717, RSPEC-5799
  _posts/python/2023-01-14-RSPEC-3923.md
  _posts/python/2023-01-14-RSPEC-5719.md
  _posts/python/2023-02-02-RSPEC-1854.md
  _posts/python/2023-02-02-RSPEC-1940.md
  _posts/python/2023-02-02-RSPEC-2710.md
  _posts/python/2023-02-02-RSPEC-5717.md
  _posts/python/2023-02-02-RSPEC-5799.md
Labels: python

#58 RSPEC-5147, RSPEC-6287, RSPEC-5334
  _posts/python/2023-02-05-RSPEC-5147.md
  _posts/python/2023-02-05-RSPEC-5334.md
  _posts/python/2023-02-05-RSPEC-6287.md
Labels: 번역, python

#59 RSPEC-1942, RSPEC-2973, RSPEC-3038, RSPEC-2156
  _posts/java/2023-02-05-RSPEC-1942.md
  _posts/java/2023-02-05-RSPEC-2156.md
  _posts/java/2023-02-05-RSPEC-2973.md
  _posts/java/2023-02-05-RSPEC-3038.md
Labels: 번역, confusing

#57 RSPEC-1110, RSPECT-1119, RSPEC-3398, RSPEC-3400, RSPEC-3416
  _posts/java/2023-02-03-RSPEC-1110.md
  _posts/java/2023-02-03-RSPEC-1119.md
  _posts/java/2023-02-04-RSPEC-3398.md
  _posts/java/2023-02-04-RSPEC-3400.md
  _posts/java/2023-02-04-RSPEC-3416.md
Labels: 번역, ⭐ 리뷰 반영했어요 ⭐, confusing

#53 RSPEC-6068, RSPEC-5853, RSPEC-5838, RSPEC-3577, RSPEC-2924, RSPEC-5786
  _posts/java/2023-02-02-RSPEC-2924.md
  _posts/java/2023-02-02-RSPEC-3577.md
  _posts/java/2023-02-02-RSPEC-5786.md
  _posts/java/2023-02-02-RSPEC-5838.md
  _posts/java/2023-02-02-RSPEC-5853.md
  _posts/java/2023-02-02-RSPEC-6068.md
Labels: 번역, tests, ⭐ 리뷰 반영했어요 ⭐

#66 RSPEC-3578, RSPEC, 2701, RSPEC-2698, RSPEC-2793
  _posts/java/2023-02-14-RSPEC-2698.md
  _posts/java/2023-02-14-RSPEC-2701.md
  _posts/java/2023-02-14-RSPEC-3578.md
  _posts/java/2023-02-14-RSPEC-5793.md
Labels: 번역, tests

#67 RSPEC-1066, RSPEC-2153
  _posts/java/2023-02-15-RSPEC-1066.md
  _posts/java/2023-02-15-RSPEC-2153.md
Labels: 번역, clumsy

#65 RSPEC-1193, RSPEC-2139, RSPEC-2185
  _posts/java/2023-02-13-RSPEC-2121.md
  _posts/java/2023-02-13-RSPEC-2440.md
  _posts/java/2023-02-13-RSPEC-2442.md
  _posts/java/2023-02-14-RSPEC-1193.md
  _posts/java/2023-02-14-RSPEC-2139.md
  _posts/java/2023-02-14-RSPEC-2185.md
Labels: 번역, clumsy

#68 RSPEC-107, RSPEC-135, RSPEC-1541
  _posts/java/2023-02-15-RSPEC-107.md
  _posts/java/2023-02-15-RSPEC-135.md
  _posts/java/2023-02-15-RSPEC-1541.md
Labels: 번역, brain-overload

#64 RSPEC-5979, RSPEC-6073, RSPEC-5977, RSPEC-3414, RSPEC-3658
  _posts/java/2023-02-13-RSPEC-3414.md
  _posts/java/2023-02-13-RSPEC-3658.md
  _posts/java/2023-02-13-RSPEC-5977.md
  _posts/java/2023-02-13-RSPEC-5979.md
  _posts/java/2023-02-13-RSPEC-6073.md
Labels: 번역, tests, ⭐ 리뷰 반영했어요 ⭐

#69 docs: RSPEC-4034, RSPEC-4719
  _posts/java/2023-02-15-RSPEC-4034.md
  _posts/java/2023-02-15-RSPEC-4719.md
Labels: 번역, clumsy

#70 RSPEC-134, RSPEC-1067, RSPEC-1820, RSPEC-1996, RSPEC-2972, RSPEC-3030
  _posts/java/2023-02-18-RSPEC-1067.md
  _posts/java/2023-02-18-RSPEC-134.md
  _posts/java/2023-02-18-RSPEC-1820.md
  _posts/java/2023-02-18-RSPEC-1996.md
  _posts/java/2023-02-18-RSPEC-2972.md
  _posts/java/2023-02-18-RSPEC-3030.md
Labels: 번역, brain-overload

#71 docs: RSPEC-3626, RSPEC-3878
  _posts/java/2023-02-19-RSPEC-3626.md
  _posts/java/2023-02-19-RSPEC-3878.md
Labels: 번역, clumsy

#74 Trans/python vulnerability 2023 02 24
  _posts/python/2023-02-22-RSPEC-2755.md
  _posts/python/2023-02-22-RSPEC-3649.md
  _posts/python/2023-02-22-RSPEC-5131.md
  _posts/python/2023-02-22-RSPEC-5135.md
  _posts/python/2023-02-22-RSPEC-5146.md
  _posts/python/2023-02-24-RSPEC-2076.md
  _posts/python/2023-02-24-RSPEC-2078.md
  _posts/python/2023-02-24-RSPEC-2083.md
  _posts/python/2023-02-24-RSPEC-2091.md
  _posts/python/2023-02-24-RSPEC-2115.md
Labels: python, vulnerability

#72 컨트리뷰터 목록 표기 방식 변경
  README.md
Labels: 문서개선

#75 docs: RSPEC-2147, RSPEC-2293, RSPEC-2737, RSPEC-2786, RSPEC-3012
  _posts/java/2023-02-26-RSPEC-2147.md
  _posts/java/2023-02-26-RSPEC-2293.md
  _posts/java/2023-02-26-RSPEC-2737.md
  _posts/java/2023-02-26-RSPEC-2786.md
  _posts/java/2023-02-26-RSPEC-3012.md
Labels: 번역, clumsy
