Repository kantabile/sonarkube, pull requests merged in 2023-01, with the labels that each got.

#7 docs: RSPEC-2308, RSPEC-2864, RSPEC-3631
  _posts/2022-12-29-RSPEC-2203.md
  _posts/2022-12-30-RSPEC-3958.md
  _posts/2023-01-02-RSPEC-2308.md
  _posts/2023-01-02-RSPEC-2864.md
  _posts/2023-01-02-RSPEC-3631.md
Labels: 번역, performance

#8 docs: RSPEC-2165, RSPEC-2232, RSPEC-2629, RSPEC-4929, RSPEC-5361
  _posts/2023-01-03-RSPEC-2165.md
  _posts/2023-01-03-RSPEC-2232.md
  _posts/2023-01-03-RSPEC-2629.md
  _posts/2023-01-03-RSPEC-4929.md
  _posts/2023-01-03-RSPEC-5361.md
Labels: 번역, performance

#9 RSPEC-6433 | 중요한 파일 시스템 경로 마운팅
  _posts/2023-01-03-RSPEC-6433.md
Labels: kubernetes

#10 docs: RSPEC-2112, RSPEC-2250, RSPEC-2276, RSPEC- 4349, RSPEC-5164
  _posts/2023-01-04-RSPEC-2112.md
  _posts/2023-01-04-RSPEC-2250.md
  _posts/2023-01-04-RSPEC-2276.md
  _posts/2023-01-04-RSPEC-4349.md
  _posts/2023-01-04-RSPEC-5164.md
Labels: 번역, performance

#12 docs: RSPEC-2970
  Gemfile.lock
  _posts/2023-01-04-RSPEC-2970.md
Labels: tests

#14 docs : RSPEC-4502, RSPEC-4790
  _posts/java/2022-12-29-RSPEC-2203.md
  _posts/java/2022-12-29-RSPEC-2229.md
  _posts/java/2022-12-29-RSPEC-3753.md
  _posts/java/2022-12-29-RSPEC-4602.md
  _posts/java/2022-12-30-RSPEC-1602.md
  _posts/java/2022-12-30-RSPEC-1604.md
  _posts/java/2022-12-30-RSPEC-1610.md
  _posts/java/2022-12-30-RSPEC-1611.md
  _posts/java/2022-12-30-RSPEC-1612.md
  _posts/java/2022-12-30-RSPEC-1711.md
  _posts/java/2022-12-30-RSPEC-2093.md
  _posts/java/2022-12-30-RSPEC-2143.md
  _posts/java/2022-12-30-RSPEC-2211.md
  _posts/java/2022-12-30-RSPEC-2718.md
  _posts/java/2022-12-30-RSPEC-2789.md
  _posts/java/2022-12-30-RSPEC-3436.md
  _posts/java/2022-12-30-RSPEC-3437.md
  _posts/java/2022-12-30-RSPEC-3649.md
  _posts/java/2022-12-30-RSPEC-3725.md
  _posts/java/2022-12-30-RSPEC-3824.md
  _posts/java/2022-12-30-RSPEC-3864.md
  _posts/java/2022-12-30-RSPEC-3958.md
  _posts/java/2022-12-30-RSPEC-3959.md
  _posts/java/2022-12-30-RSPEC-4065.md
  _posts/java/2022-12-30-RSPEC-4601.md
  _posts/java/2022-12-30-RSPEC-4684.md
  _posts/java/2022-12-30-RSPEC-4738.md
  _posts/java/2022-12-30-RSPEC-5344.md
  _posts/java/2022-12-30-RSPEC-5876.md
  _posts/java/2023-01-02-RSPEC-2308.md
  _posts/java/2023-01-02-RSPEC-2864.md
  _posts/java/2023-01-02-RSPEC-3631.md
  _posts/java/2023-01-05-RSPEC-4502.md
  _posts/java/2023-01-05-RSPEC-4790.md
Labels: spring

#16 Trans/kubernetes 2023 01 04
  _posts/2023-01-04-RSPEC-2260.md
  _posts/2023-01-04-RSPEC-5849.md
  _posts/2023-01-04-RSPEC-6428.md
  _posts/2023-01-04-RSPEC-6429.md
  _posts/2023-01-04-RSPEC-6430.md
  _posts/2023-01-04-RSPEC-6431.md
Labels: 번역, kubernetes

#17 docs: RSPEC-2130, RSPEC-2153, RSPEC-4635
  _posts/2023-01-07-RSPEC-1149.md
  _posts/2023-01-07-RSPEC-1158.md
  _posts/2023-01-07-RSPEC-2130.md
  _posts/2023-01-07-RSPEC-2153.md
  _posts/2023-01-07-RSPEC-4635.md
Labels: 번역, performance

#18 RSPEC-1641, RSPEC-1643, RSPEC-4248
  _posts/2023-01-08-RSPEC-1641.md
  _posts/2023-01-08-RSPEC-1643.md
  _posts/2023-01-08-RSPEC-4248.md
Labels: 번역, performance

#20 RSPEC-5783, RSPEC-5779
  _posts/2023-01-10-RSPEC-5779.md
  _posts/2023-01-10-RSPEC-5783.md
Labels: tests

#30 RSPEC-1132, RSPEC-1310, RSPEC-1315, RSPEC-1291
  _posts/java/2023-01-14-RSPEC-1132.md
  _posts/java/2023-01-14-RSPEC-1291.md
  _posts/java/2023-01-14-RSPEC-1310.md
  _posts/java/2023-01-14-RSPEC-1315.md
Labels: bad practice

#28 RSPEC-1214, RSPEC-1215
  .gitignore
  _posts/java/2023-01-07-RSPEC-1214.md
  _posts/java/2023-01-07-RSPEC-1215.md
Labels: bad practice

#19 RSPEC-2699, RSPEC-2188, RSPEC-2187, RSPEC-5845, RSPEC-5790
  _posts/2023-01-09-RSPEC-2187.md
  _posts/2023-01-09-RSPEC-2188.md
  _posts/2023-01-09-RSPEC-2699.md
  _posts/2023-01-09-RSPEC-5790.md
  _posts/2023-01-09-RSPEC-5845.md
  _posts/java/2023-01-04-RSPEC-2970.md
Labels: tests, ⭐ 리뷰 반영했어요 ⭐

#21 RSPEC-5969, RSPEC-5826, RSPEC-2186
  _posts/2023-01-11-RSPEC-2186.md
  _posts/2023-01-11-RSPEC-5826.md
  _posts/2023-01-11-RSPEC-5969.md
Labels: tests

#22 RSPEC-6103, RSPEC-5967
  _posts/2023-01-12-RSPEC-5967.md
  _posts/2023-01-12-RSPEC-6103.md
Labels: tests, ⭐ 리뷰 반영했어요 ⭐

#31 RSPEC-2230, RSPEC-3305, RSPEC-5679, RSPEC-5804 및 일부 수정사항
  CONTRIBUTING.md
  _posts/java/2022-12-29-RSPEC-2203.md
  _posts/java/2022-12-30-RSPEC-1602.md
  _posts/java/2022-12-30-RSPEC-1604.md
  _posts/java/2022-12-30-RSPEC-1610.md
  _posts/java/2022-12-30-RSPEC-1611.md
  _posts/java/2022-12-30-RSPEC-1612.md
  _posts/java/2022-12-30-RSPEC-1711.md
  _posts/java/2022-12-30-RSPEC-2093.md
  _posts/java/2022-12-30-RSPEC-2143.md
  _posts/java/2022-12-30-RSPEC-2211.md
  _posts/java/2022-12-30-RSPEC-2718.md
  _posts/java/2022-12-30-RSPEC-2789.md
  _posts/java/2022-12-30-RSPEC-3436.md
  _posts/java/2022-12-30-RSPEC-3437.md
  _posts/java/2022-12-30-RSPEC-3725.md
  _posts/java/2022-12-30-RSPEC-3824.md
  _posts/java/2022-12-30-RSPEC-3864.md
  _posts/java/2022-12-30-RSPEC-3958.md
  _posts/java/2022-12-30-RSPEC-3959.md
  _posts/java/2022-12-30-RSPEC-4065.md
  _posts/java/2022-12-30-RSPEC-4738.md
  _posts/java/2023-01-02-RSPEC-2308.md
  _posts/java/2023-01-02-RSPEC-2864.md
  _posts/java/2023-01-02-RSPEC-3631.md
  _posts/java/2023-01-03-RSPEC-2165.md
  _posts/java/2023-01-03-RSPEC-2232.md
  _posts/java/2023-01-03-RSPEC-2629.md
  _posts/java/2023-01-03-RSPEC-4929.md
  _posts/java/2023-01-03-RSPEC-5361.md
  _posts/java/2023-01-04-RSPEC-2112.md
  _posts/java/2023-01-04-RSPEC-2250.md
  _posts/java/2023-01-04-RSPEC-2276.md
  _posts/java/2023-01-04-RSPEC-4349.md
  _posts/java/2023-01-04-RSPEC-5164.md
  _posts/java/2023-01-05-RSPEC-2129.md
  _posts/java/2023-01-05-RSPEC-2694.md
  _posts/java/2023-01-05-RSPEC-4276.md
  _posts/java/2023-01-05-RSPEC-4502.md
  _posts/java/2023-01-05-RSPEC-4790.md
  _posts/java/2023-01-06-RSPEC-1640.md
  _posts/java/2023-01-06-RSPEC-2133.md
  _posts/java/2023-01-06-RSPEC-3047.md
  _posts/java/2023-01-07-RSPEC-1149.md
  _posts/java/2023-01-07-RSPEC-1158.md
  _posts/java/2023-01-07-RSPEC-2130.md
  _posts/java/2023-01-07-RSPEC-2153.md
  _posts/java/2023-01-07-RSPEC-4635.md
  _posts/java/2023-01-08-RSPEC-1641.md
  _posts/java/2023-01-08-RSPEC-1643.md
  _posts/java/2023-01-08-RSPEC-4248.md
  _posts/java/2023-01-10-RSPEC-5779.md
  _posts/java/2023-01-10-RSPEC-5783.md
  _posts/java/2023-01-14-RSPEC-2230.md
  _posts/java/2023-01-14-RSPEC-3305.md
  _posts/java/2023-01-14-RSPEC-5679.md
  _posts/java/2023-01-14-RSPEC-5804.md
Labels: spring, ⭐ 리뷰 반영했어요 ⭐

#32 RSPEC-2077, RSPEC-3751, RSPEC-5122
  _posts/java/2023-01-15-RSPEC-2077.md
  _posts/java/2023-01-15-RSPEC-3751.md
  _posts/java/2023-01-15-RSPEC-5122.md
Labels: spring

#35 RSPEC-1118, RSPEC-110
  _posts/java/2023-01-16-RSPEC-110.md
  _posts/java/2023-01-16-RSPEC-1118.md
Labels: 번역, ⭐ 리뷰 반영했어요 ⭐, design

#34 RSPEC-3752, RSPEC-4507
  _posts/java/2023-01-16-RSPEC-3752.md
  _posts/java/2023-01-16-RSPEC-4507.md
Labels: 번역, spring

#36 RSPEC-2092, RSPEC-4488
  _posts/java/2023-01-17-RSPEC-2092.md
  _posts/java/2023-01-17-RSPEC-4488.md
Labels: spring

#38 docs: RSPEC-2974, RSPEC-2301
  _posts/java/2023-01-18-RSPEC-2301.md
  _posts/java/2023-01-18-RSPEC-2974.md
Labels: 번역, ⭐ 리뷰 반영했어요 ⭐, design

#40 docs: RSPEC-2157, RSPEC-3242, RSPEC-4042
  _posts/java/2023-01-19-RSPEC-2157.md
  _posts/java/2023-01-19-RSPEC-3242.md
  _posts/java/2023-01-19-RSPEC-4042.md
Labels: 번역, ⭐ 리뷰 반영했어요 ⭐, api-design

#41 docs: RSPEC-5976, RSPEC-2925
  _posts/java/2023-01-24-RSPEC-2925.md
  _posts/java/2023-01-24-RSPEC-5976.md
Labels: bad practice

#37 RSPEC-3749, RSPEC-3750, RSPEC-4605
  _posts/java/2023-01-18-RSPEC-3749.md
  _posts/java/2023-01-18-RSPEC-3750.md
  _posts/java/2023-01-18-RSPEC-4605.md
Labels: spring

#45 docs: RSPEC-1994, RSPEC-3252, RSPEC-3973
  _posts/java/2023-01-27-RSPEC-1994.md
  _posts/java/2023-01-27-RSPEC-3252.md
  _posts/java/2023-01-27-RSPEC-3973.md
Labels: 번역, confusing

#47 RSPEC-5863, RSPEC-5833, RSPEC-5831, RSPEC-5810, RSPEC-5973
  _posts/java/2023-01-27-RSPEC-5810.md
  _posts/java/2023-01-27-RSPEC-5831.md
  _posts/java/2023-01-27-RSPEC-5833.md
  _posts/java/2023-01-27-RSPEC-5863.md
  _posts/java/2023-01-27-RSPEC-5973.md
Labels: tests, ⭐ 리뷰 반영했어요 ⭐
